---
- name: 'Check ansible version >= 2.0'
  assert:
    that:
    - 'ansible_version.major is number'
    - 'ansible_version.major >= 2'

- name: Set-up apt-repository (when needed)
  include: apt-repository.yml
  when: posgresql_add_repository

- name: Install postgresql
  apt:
    name: "{{ item }}"
    state: "present"
  with_items: '{{ postgresql_deb_packages }}'
  notify: restart postgresql

- name: Create database dir
  shell: '{{ postgresql_bindir }}/initdb {{ postgresql_initdb_params }} --pgdata={{ postgresql_datadir }}'
  args:
      creates: '{{ postgresql_datadir }}/base'
  when: postgresql_init_database
  become: yes
  become_user: '{{ postgresql_user }}'