---
- name: 'Check ansible version >= 2.0'
  assert:
    that:
    - 'ansible_version.major is number'
    - 'ansible_version.major >= 2'

- name: Set-up apt-repository (when needed)
  include: apt-repository.yml
  when: posgresql_add_repository

- name: Install postgresql
  apt:
    name: "{{ item }}"
    state: "present"
  with_items: postgresql_deb_packages
  notify: restart postgresql
