---
# tasks file for postgresql

- name: apt-get update
  apt: update_cache=yes cache_valid_time=3600
  tags: postgresql

- name: apt-get install
  apt: name={{ item }} state=latest
  with_items:
    - postgresql
    - python-psycopg2
  tags: postgresql
