---
# tasks file for postgresql

- name: Check ansible version
  ping:

- name: Add apt repository (when needed)
  apt_key:
    url: "{{ item.apt_key }}"
    state: "{{ item.state|default('present') }}"
  with_items: postgresql_apt_repository
  when: posgresql_add_repository

- name: Add apt repository (when needed)
  apt_repository:
    repo: "{{ item.repository_url }}"
    state: "{{ item.state|default('present') }}"
  with_items: postgresql_apt_repository
  when: posgresql_add_repository

- name: Install postgresql
  apt:
    name: "{{ item }}"
    state: "present"
  with_items: postgresql_deb_packages
  notify: restart postgresql

- name: Upload config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "postgres"
    group: "postgres"
    mode: "0644"
    backup: yes
  with_items:
    - src: "pg_hba.conf.j2"
      dest: "/etc/postgresql/9.5/main/pg_hba.conf"
    - src: "postgresql.conf.j2"
      dest: "/etc/postgresql/9.5/main/postgresql.conf"
  notify: restart postgresql

- name: enable service
  service:
    name: "postgresql"
    enabled: "yes"
  notify: restart postgresql
