---
# tasks file for hswong3i.postgresql

- name: apt-get install
  apt:
    name="{{ item }}"
    state=latest
  with_items:
    - libdbd-pg-perl
    - postgresql
    - python-psycopg2
    - ufw
  notify: restart postgresql
  tags: hswong3i.postgresql

- name: copy templates
  template:
    src={{ item.src }}
    dest={{ item.dest }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
  with_items:
    - { src: 'etc/postgresql/9.3/main/pg_hba.conf.j2', dest: '/etc/postgresql/9.3/main/pg_hba.conf',  owner: 'postgres', group: 'postgres', mode: '0644' }
    - { src: 'etc/postgresql/9.3/main/postgresql.conf.j2', dest: '/etc/postgresql/9.3/main/postgresql.conf',  owner: 'postgres', group: 'postgres', mode: '0644' }
  notify: restart postgresql
  tags: hswong3i.postgresql

- name: enable service
  service: name=postgresql enabled=yes
  notify: restart postgresql
  tags: hswong3i.postgresql

- name: enable incomming connection
  ufw:
    to_port={{ item }}
    proto=tcp
    rule=allow
  with_items:
    - "{{ postgresql_port }}"
  notify: restart postgresql
  tags: hswong3i.postgresql
