---
# tasks file for postgresql

- name: apt-get install
  apt: name={{ item }} state=latest
  with_items:
    - postgresql
    - python-psycopg2
  notify: restart postgresql
  tags: postgresql

- name: enable service
  service: name=postgresql enabled=yes
  notify: restart postgresql
  tags: postgresql
