---
- name: 'Check ansible version >= 2.0'
  assert:
    that:
    - 'ansible_version.major is number'
    - 'ansible_version.major >= 2'

- name: Set-up apt-repository (when needed)
  include: apt-repository.yml
  when: posgresql_add_repository

- name: Install postgresql
  apt:
    name: "{{ item }}"
    state: "present"
  with_items: postgresql_deb_packages
  notify: restart postgresql

- name: Upload config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "postgres"
    group: "postgres"
    mode: "0644"
    backup: yes
  with_items:
    - src: "pg_hba.conf.j2"
      dest: "/etc/postgresql/9.5/main/pg_hba.conf"
    - src: "postgresql.conf.j2"
      dest: "/etc/postgresql/9.5/main/postgresql.conf"
  notify: restart postgresql

- name: enable service
  service:
    name: "{{ postgresql_service }}"
    enabled: "yes"
    state: "started"
  notify: restart postgresql
  ignore_errors: '{{ postgresql_ignore_start_errors }}'
